baseURL = ""
title = "Michele Schimd personal website"
author = "Michele Schimd"
theme = "hugo-theme-monochrome"

[params]
enable_math = true
navbar_title = "Michele Schimd"
footer = "Copyright © 2024 by Michele Schimd" 



defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    contentDir = "content/"
    disabled = false
    languageCode = "en"
    languageName = "English"
    weight = 1
    [[menu.navbar]]
      identifier = "about"
      name = "about"
      title = "about"
      url = "about"
      weight = 100
  [languages.it]
    contentDir = "content/it"
    disabled = false
    languageCode = "it"
    languageName = "Italiano"
    weight = 2
    title = "Blog di Michele Schimd"
    [[menu.navbar]]
      identifier = "about"
      name = "about"
      title = "about"
      url = "about"
      weight = 100


